[[redirects]]
  from = "/api/*"
  to = "https://kitaba.kaaf.me/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bg/*"
  to = "https://3rabapp.com/apps/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true